// Generated by CoffeeScript 1.6.3
(function() {
  this.Questions = Backbone.Collection.extend({
    model: Question,
    url: "question",
    db: {
      view: "questionsByAssessmentId"
    }
  });

}).call(this);
