// Generated by CoffeeScript 1.6.3
(function() {
  this.Question = Backbone.Model.extend({
    url: "question",
    config: {
      types: ["multiple", "single", "open"]
    },
    defaults: {
      order: 0,
      prompt: "Is this an example question?",
      hint: "[hint or answer]",
      type: "single",
      otherWriteIn: false,
      options: [],
      linkedGridScore: 0,
      skipLink: null,
      skipRequirement: null
    },
    initialize: function(options) {
      return console.log("Initialized Question Model With Some Defaults Fields");
    }
  });

}).call(this);
