// Generated by CoffeeScript 1.6.3
(function() {
  this.Config = {};

  this.Config = {
    "db_name": "backbone",
    "design_doc": "tangerinesam"
  };

  Backbone.couch_connector.config.db_name = Config.db_name;

  Backbone.couch_connector.config.ddoc_name = Config.design_doc;

  Backbone.couch_connector.config.global_changes = true;

  _.templateSettings = {
    interpolate: /\{\{(.+?)\}\}/g
  };

  Config.$db = $.couch.db(Config.db_name);

  Config.$db.openDoc("Config", {
    success: function(data) {
      return Config.config = data;
    }
  }, {
    async: false
  });

  Config.$db.openDoc("TangerineSettings", {
    success: function(data) {
      return Config.settings = data;
    },
    error: function(code) {
      if (code === 404) {
        return Config.$db.openDoc("TangerineSettingsDefault", {
          success: function(doc) {
            doc._id = "TangerineSettings";
            doc._rev = void 0;
            Config.settings = doc;
            return Config.$db.saveDoc(doc);
          }
        }, {
          async: false
        });
      }
    }
  }, {
    async: false
  });

}).call(this);
