// Generated by CoffeeScript 1.6.3
(function() {
  this.AssessmentView = Backbone.View.extend({
    tagName: 'table',
    template: null,
    initialize: function() {
      return this.template = Handlebars.compile($("#entry-template").html());
    },
    render: function() {
      console.log("Rendering AssessmentView");
      this.$el.html(this.template(this.collection.toJSON()));
      return this;
    }
  });

}).call(this);
