// Generated by CoffeeScript 1.6.3
(function() {
  this.Assessments = Backbone.Collection.extend({
    model: Assessment,
    url: 'assessment',
    initialize: function(options) {
      return console.log("Intialized Assessments Collection");
    }
  });

}).call(this);
