// Generated by CoffeeScript 1.6.3
(function() {
  this.Assessment = Backbone.Model.extend({
    url: 'assessment',
    initialize: function(options) {
      if (options == null) {
        options = {};
      }
      return console.log("initialize Assessment Model");
    }
  });

}).call(this);
