// Generated by CoffeeScript 1.6.3
(function() {
  this.AssessmentView = Backbone.View.extend({
    model: Assessment,
    initialize: function() {
      return this.render();
    },
    render: function() {
      return console.log("Rendering AssessmentView");
    }
  });

}).call(this);
