// Generated by CoffeeScript 1.6.3
(function() {
  this.AssessmentView = Backbone.View.extend({
    tagName: 'table',
    template: null,
    initialize: function() {
      return this.template = _.template("<% print('Hello ' + epithet); %>");
    },
    render: function() {
      console.log("Rendering AssessmentView");
      this.$el.html(this.template({
        epithet: "stooge"
      }));
      return this;
    }
  });

}).call(this);
